# 消息中心
"msg-center":
  icon: center
  sort: 2
  site:
    - "send-setting":
        icon: mail_set
        Routes: /notify/send-setting
        sort: 1
        permission:
        - 'notify-service.send-setting-site.pageSite'
    - "mail-template":
        icon: application_model
        Routes: /notify/mail-template
        sort: 2
        permission:
        - 'notify-service.email-template-site.pageSite'
        - 'notify-service.email-template-site.create'
        - 'notify-service.email-template-site.update'
        - 'notify-service.email-template-site.query'
        - 'notify-service.send-setting-site.listNames'
    - "inmail-template":
        icon: inmail_template
        Routes: /notify/inmail-template
        sort: 3
        permission:
        - 'notify-service.pm-template-site.pageSite'
        - 'notify-service.pm-template-site.create'
        - 'notify-service.pm-template-site.update'
        - 'notify-service.pm-template-site.query'
        - 'notify-service.send-setting-site.listNames'
    - "mail-setting":
        icon: contact_mail
        Routes: /notify/mail-setting
        sort: 4
        permission:
        - 'notify-service.config.selectEmail'
        - 'notify-service.config.testEmailConnect'
        - 'notify-service.config.updateEmail'
    - "msg-record":
        icon: speaker_notes
        Routes: /notify/msg-record
        sort: 5
        permission:
        - 'notify-service.message-record-site.pageEmail'
    - "announcement":
        icon: volume_up
        Routes: /notify/announcement
        sort: 6
        permission:
        - 'notify-service.system-announcement.pagingQuery'
        - 'notify-service.system-announcement.create'
        - 'notify-service.system-announcement.update'
        - 'notify-service.system-announcement.delete'

# 个人中心
"usercenter":
  icon: accessibility
  sort: 1
  user:
    - "user-msg":
        icon: message_notification
        Routes: /notify/user-msg
        sort: 6
        permission:
          - 'notify-service.site-msg-record.pagingQuery'
          - 'notify-service.site-msg-record.batchDeleted'
          - 'notify-service.site-msg-record.batchRead'
          - 'notify-service.system-announcement.pagingQueryCompleted'
    - "receive-setting":
        icon: settings
        Routes: /notify/receive-setting
        sort: 7
        permission:
          - 'notify-service.receive-setting.queryByUserId'
          - 'notify-service.receive-setting.updateByUserId'
          - 'notify-service.receive-setting.update'
